[package]
name = "core"
version = "0.1.0"
edition.workspace = true

[dependencies]
common = { path = "../common" }

webpki-roots = { version = "0.26.1", optional = true }

[features]
webpki = ["webpki-roots"]